[toolchain]
# There were some issues with other nightly channels, either the
# __ashlti3 https://github.com/rust-lang/rust/issues/106135 or
# incompatible symbols.o: https://github.com/Rahix/avr-hal/issues/388
# This one worked for both mikrocontrollers I used
channel = "nightly-2022-10-22"
components = ["rust-src"]
profile = "minimal"
