[build]
target = ["avr-specs/avr-atmega2560.json", "avr-specs/avr-attiny85.json"]

[target.avr-atmega2560]
runner = "ravedude mega2560 -cb 57600"

[target.avr-attiny85]
runner = "ravedude tiny85"
rustflags = [
"-C", "inline-threshold=275"]

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[unstable]
build-std = ["core"]
multitarget = true
