[build]
target = ["avr-specs/avr-atmega2560.json", "avr-specs/avr-attiny85.json"]

[target.'cfg(target_cpu = "atmega2560")']
runner = "ravedude mega2560 -cb 57600"

[target.'cfg(target_cpu = "attiny85")']
runner = "ravedude trinket"

[unstable]
build-std = ["core"]
